---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: demodeploy
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/markusrt/gitops-deploy

